name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - "*"
jobs:
  # https://github.com/marketplace/actions/checkout-submodules
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Checkout submodules
        # uses: textbook/git-checkout-submodule-action@master
        run: git submodule update --init --recursive
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          yarn install
      - run: |
          yarn run build
      - run: |
          yarn run lint
      - run: |
          yarn run test